// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiedjtdtxhtpisisaybh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZWRqdGR0eGh0cGlzaXNheWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxODkzNTUsImV4cCI6MjA4ODc2NTM1NX0.jkD9ic6EbJnnUzROht4k6K_9PqT0EX6ENsYpYG5iKU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});